# Generated by Django 6.0.4 on 2026-05-03 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('midname', models.CharField(blank=True, max_length=100)),
                ('busname', models.CharField(blank=True, max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=200)),
                ('npi', models.CharField(blank=True, max_length=20)),
                ('excltype', models.CharField(blank=True, max_length=100)),
                ('excldate', models.CharField(blank=True, max_length=20)),
                ('reindate', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['lastname', 'firstname'], name='oig_exclude_lastnam_a28739_idx'), models.Index(fields=['npi'], name='oig_exclude_npi_4d6d53_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('npi', models.CharField(blank=True, max_length=20)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
